# Generated by Django 2.0.7 on 2018-07-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_ratio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
