# Generated by Django 2.0.7 on 2018-07-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_reading_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reading_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
